# Generated by Django 5.2.4 on 2025-07-28 08:23

import django.utils.timezone
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(upload_to=movies.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=movies.models.thumbnail_upload_path)),
            ],
        ),
    ]
